package com.tweetapp.bean.user;

import java.io.Serializable;

import org.springframework.data.mongodb.core.mapping.Document;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "userInfo")
public class UserInfoBean implements Serializable {
	private static final long serialVersionUID = -7091553609909608L;
	
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	@DynamoDBAttribute
	private String firstName;
	@DynamoDBAttribute
	private String lastName;
	@DynamoDBAttribute
	private String loginId;
	@DynamoDBAttribute
	private String emailId;
	@DynamoDBAttribute
	private String password;
	@DynamoDBAttribute
	private String contactNumber;
	
}
